spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:h2:mem:jimslog
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

  data:
    redis:
      port: 6379
      host: ${REDIS_HOST}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${AWS_REGION_STATIC}
    stack:
      auto: false
    credentials:
      access-key: ${AWS_CREDENTIALS_ACCESS_KEY}
      secret-key: ${AWS_CREDENTIALS_SECRET_KEY}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

jimslog:
  admin: ${JIMSLOG_ADMIN}
  s3:
    url: ${JIMSLOG_S3_URL}
    local: ${JIMSLOG_S3_LOCAL}

schedules :
  cron :
    post-images :
      delete : 0 0 4 * * *
  post-images :
    limit-time : 86400