spring:
  datasource:
    url: jdbc:h2:mem:jimslog
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

schedules :
  cron :
    post-images :
      delete : 0 0 4 * * *
  post-images :
    limit-time : 86400

---

spring:
  profiles:
    include:
      - secret
      - aws
      - credentials